Update install
YunoHost-Apps/misskey_ynh pull request #82
Opened 2022-04-19 14:56 UTC by memo-567

Stop the installation script if the system is not x64.

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

2022-04-19 14:59 UTC, memo-567 commented
!testme

2022-04-21 18:14 UTC, tituspijean requested changes

2022-04-21 18:14 UTC, tituspijean commented on scripts/install
> +fi
```suggestion
if [ $YNH_ARCH != "amd64" ] && [ $YNH_ARCH ! "aarch64" ] && [ $YNH_ARCH != "arm64" ]
then
	ynh_die --message="Sorry, but this app can only be installed on a 64 bits machine :("
fi
```

Let's test the other way around and list the compatible architectures. ;)

2022-04-21 18:28 UTC, memo-567 commented
!testme

2022-04-22 04:54 UTC, merged